name: Deploy production version of the Website on Current Repo

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  Build-And-Deploy-Production:
    if: ${{ github.repository_owner == 'path-cc' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Initialize GH User
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Build and Deploy
        run: |
          # Build the production version of website
          JEKYLL_ENV=production bundle exec jekyll build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./_site # The folder the action should deploy.

