name: Check Links
on: push

jobs:
  Check-Website-Links:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Build Jekyll Site
        shell: bash
        run: |
          bundle install
          bundle exec jekyll build

      - name: Ensure jq is installed
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      # This step fetches and processes URLs and sets them as an output variable
      - name: Fetch and process URLs
        id: set-urls
        run: |
          urls=$(curl -s https://raw.githubusercontent.com/CannonLock/link_checker_config/main/ignore_urls.json | jq -r 'map("/" + . + "/") | join(",")' | sed 's/ //g')
          echo "::set-output name=urls::$urls"

      # Use the output from the previous step as input for your action
      - uses: CannonLock/test_links@master
        with:
          url_ignore: "${{ steps.set-urls.outputs.urls }}"
