name: Update Submodules
on: workflow_dispatch

jobs:

  Update-Submodules:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name:
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git submodule update --remote --merge
          git add .github/workflows/update-submodules.yml
          git commit -m "Update Submodules"
          git push
